# -*- coding: utf-8 -*-
"""01-Kelompok F-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gShnU0hC3PCt5gnJiPurcasAMujpNY3x
"""

import pandas as pd
pd.set_option('display.max_columns', None)

data = pd.read_csv('https://raw.githubusercontent.com/Rietaros/kampus_merdeka/main/HRDataset_v14.csv')
data.head()

"""# Pandas Question

1. What is the minimum, median, max, and average salary for employee by Married Description and Gender.
Hints: use agg function<br>
Expected Output as below<br>
(10 Points)
"""

# 1. What is the minimum, median, max, and average salary for employee by Married Description and Gender
# Hints: use agg function
# Expected Output as below
# (10 Points)

data.groupby(by=['MaritalDesc','Sex'])\
    .agg(min_salary=('Salary','min'),
         median_salary=('Salary','median'),
         max_salary=('Salary','max'),
         average_salary=('Salary','mean'))

"""2. What is top-5 reason of termination?<br>
Expected Output as below<br>
(10 Points)
"""

#code here
data['TermReason'].value_counts().head(5).rename('total_result', inplace=True)

"""3. What is the highest number of employee by Recruitment Source that 'Exceeds' the Performance Score?
Hints: Use filter for Performance Score first. Don't forget to sort_values.<br>
Expected Output as below<br>
(10 Points)
"""

#code here
data[data['PerformanceScore']=='Exceeds'].filter(items=['RecruitmentSource']).value_counts().head(7).rename('total_result', inplace=True)

"""4. How many managers in each department?
Hints: use nunique() as aggregation function.<br>
Expected Output as below.<br>
(10 Points)
"""

#code here
data.groupby(by=['Department']).agg(total_manager=('ManagerName','nunique'))

"""5. What is Termination Ratio by Gender?.
Hints: use value_counts(normalize=True).<br>
Expected Output as below.<br>
(10 Points)
"""

#code here
print(data.groupby(by=['Sex'])['Termd'].value_counts(normalize=True).rename('Termd'))

"""# Create an EDA and Data Visualization Question"""

#Sample Visualization, the example is not counted for the final score :p
#Create 5 visualization for better understanding on data
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np

#Ratio termination by Gender

#Step1, get the data

term = data.groupby(by=['Sex'])\
                        .agg(total_termination=('Termd','sum')).reset_index()\

#Step2, Plot it
f, ax = plt.subplots(1, 1, figsize=(12, 8))
ax = sns.barplot(x='Sex', y='total_termination', hue='Sex', data=term, palette='cool')

"""6. Buatlah Scatter plot antara kolom "Salary" dengan "EngagementSurvey", beri warna berbeda sesuai dengan status di "Termd"<br>
(5 points)<br>
*bentuk output di bawah hanya contoh*
"""

#code here
sns.scatterplot(x='Salary', y='EngagementSurvey', hue='Termd', data=data)

"""7. Buatlah visualisasi barchart untuk menghitung jumlah "termination of an employee's" berdasarkan department.<br>
(5 points)<br>
*bentuk output di bawah hanya contoh*
"""

dbarchart = data.groupby(by=['Department']).agg(total_termination=('Termd','sum')).sort_values(by='total_termination', ascending=False)

sns.barplot(x='total_termination', y='Department', hue="Department", data=dbarchart)

"""8. Buatlah visualisasi Pie Chart untuk melihat persentasi jumlah karyawan yang "terminated" berdasarkan kolom "Position".<br>
(5 points)<br>
*bentuk output di bawah hanya contoh*
"""

dpai = data.groupby(by=['Position']).agg(total_termination=('Termd','sum')).sort_values(by='total_termination', ascending=False)
dpai = dpai[dpai['total_termination'] != 0]

sns.set(font_scale=0.6)
plt.pie(dpai['total_termination'], labels=dpai.index, autopct='%1.1f%%')
plt.show()

"""9. Buat Boxplot yang menggambarkan Salary berdasarkan Marital Desc, bedakan berdasarkan Termd
(5 points)
"""

#code here
sns.boxplot(x="Salary", y='MaritalDesc', hue='Termd', data=data)

"""10. Tampilkan pairplot antara kolom 'Salary', 'EngagementSurvey', 'EmpSatisfaction','Absences'
beri kategori warna berdasarkan 'Termd'<br>
(10 points)
"""

#code here
sns.pairplot(data, hue='Termd', vars=['Salary', 'EngagementSurvey', 'EmpSatisfaction','Absences'], diag_kind='hist')

"""# Insight (Answering the Question)

11.	Is there any relationship between who a person works for (their manager) and their performance score? (10 points)<br>
12.	What are our best recruiting sources if we want to ensure a low ratio of termination? (10 points)<br>

# 11.
"""

# JAWABAN NO 11
from scipy.stats import chi2_contingency

# Visualisasikan hubungan antara ManagerName dan PerformanceScore
#plt.figure(figsize=(7,6))
sns.countplot(y='ManagerName', hue='PerformanceScore', data=data)

plt.title('Manager vs Performance Score')
plt.show()

# Buat tabel kontingensi untuk meringkas hubungan tersebut
contingency_table = pd.crosstab(data['ManagerName'], data['PerformanceScore'])

# Lakukan uji Chi-Square
chi2, p_value, dof, expected = chi2_contingency(contingency_table)


print(f"Chi-Square Statistic: {chi2}")
print(f"P-value: {p_value}")

# Interpretasi hasil
if p_value < 0.05:
    print("There is a significant relationship between Manager and Performance Score.")
else:
    print("There is no significant relationship between Manager and Performance Score.")

"""**Summary**
- Dari grafik tersebut kita tidak bisa langsung mengambil kesimpulan tanpa analisis statistik lebih lanjut. Grafik ini menunjukkan bagaimana masing-masing manajer memiliki variasi dalam skor kinerja timnya, yang dikategorikan menjadi empat jenis skor: Exceeds, Fully Meets, Needs Improvement, dan PIP. Grafik sering kali bersifat subjektif dan tidak menunjukkan kekuatan hubungan atau mempertimbangkan ukuran sampel. Untuk menguji apakah hubungan ini signifikan, kita bisa melakukan uji statistik seperti uji Chi-Square.
Berdasarkan hasil uji Chi-Square = 67, p-value = 0.2494, dan dof=60 , kita dapat menyimpulkan bahwa **TIDAK ADA HUBUNGAN SIGNIFIKAN** antara manajer dan skor kinerja karyawan. Artinya, seseorang yang bekerja (manajer) tidak secara signifikan mempengaruhi skor kinerjanya. Dikarenakan nilai p-value yang diperoleh dari uji Chi-Square adalah 0.2494, yang jauh lebih besar dari tingkat signifikansi umum 0.05. Ini berarti kita gagal menolak hipotesis nol dan tidak dapat menyimpulkan bahwa ada hubungan yang signifikan antara kedua variabel.

# 12.
"""

# JAWABAN NO 12
data.groupby(by=['RecruitmentSource']).agg(total_termination=('Termd','sum')).sort_values(by='total_termination').head()

"""**Summary**
- Berdasarkan hasil berikut dapat disimpulkan bahwa sumber perekrutan terbaik adalah On-line Web Aplication dan Website karena memiliki total pemutusan hubungan kerja yang paling sedikit dibandingkan sumber perekrutan lainnya
"""